# permissions for end users to view goddessmoments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kb
    app.kubernetes.io/managed-by: kustomize
  name: goddessmoment-viewer-role
rules:
- apiGroups:
  - kb.crd.erican.io
  resources:
  - goddessmoments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kb.crd.erican.io
  resources:
  - goddessmoments/status
  verbs:
  - get
