---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kb.crd.erican.io
  resources:
  - goddessmoments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kb.crd.erican.io
  resources:
  - goddessmoments/finalizers
  verbs:
  - update
- apiGroups:
  - kb.crd.erican.io
  resources:
  - goddessmoments/status
  verbs:
  - get
  - patch
  - update
